<?php echo $this->doctype(); ?>
<html lang="en" ng-app="SiteApp">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>EFont</title>
    <!-- BEGIN STYLES -->
    <link href="<?php echo $this->basePath(); ?>/bower_components/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet">
    <link href="<?php echo $this->basePath(); ?>/bower_components/animate.css/animate.min.css" rel="stylesheet" type="text/css" />
    <link href="<?php echo $this->basePath(); ?>/bower_components/angular-loading-bar/build/loading-bar.min.css" media="all" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $this->basePath(); ?>/bower_components/angular/angular-csp.css" rel="stylesheet" type="text/css"/>
    <link href="<?php echo $this->basePath(); ?>/css/style.css" rel="stylesheet">
    <!-- END STYLES -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body ng-cloak>
	<!-- BEGIN MENU -->
	   <nav class="navbar navbar-inverse navbar-static-top">
	    <div class="container">
	      <div class="navbar-header">
	        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
	          <span class="sr-only">Toggle navigation</span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	          <span class="icon-bar"></span>
	        </button>
	        <a class="navbar-brand text-hide" href="javascript:;"><img alt="" src="https://cdn.worldvectorlogo.com/logos/bootstrap-5.svg" /></a>
	      </div>
	      <div id="navbar" class="navbar-collapse collapse">
	        <ul class="nav navbar-nav navbar-right">
	          <li class="active"><a href="#">Home</a></li>
	          <li><a href="#">About</a></li>
	          <li><a href="#">Contact</a></li>
	        </ul>
	      </div>
	      <!--/.nav-collapse -->
	    </div>
	    <!--/.container-fluid -->
	  </nav>
	<!-- END MENU -->
  	<!-- BEGIN CONTENT -->
  	<?php echo $this->content; ?>
	<!-- END CONTENT -->  
  	<!-- BEGIN FOOTER -->
    <footer class="footer">
      <div class="container">
        <p class="text-muted">Footer</p>
      </div>
    </footer>
  	<!-- END FOOTER -->
	<!-- BEGIN JS --> 
    <script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/jquery/dist/jquery.min.js"></script>    
	<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/jquery-ui/jquery-ui.min.js"></script>		
	<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular/angular.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/bootstrap/dist/js/bootstrap.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-i18n/angular-locale_pt-br.js"></script>
	<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-sanitize/angular-sanitize.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/angular-loading-bar/build/loading-bar.min.js"></script>
	<script type="text/javascript" src="<?php echo $this->basePath(); ?>/bower_components/ngstorage/ngStorage.min.js"></script>
    
    <script src="<?php echo $this->basePath(); ?>/js/functions.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/message.js"></script>
    
    <script src="<?php echo $this->basePath(); ?>/js/app/SiteApp.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/app/directives/directive.js"></script>
    <script src="<?php echo $this->basePath(); ?>/js/app/controllers/SiteCtrl.js"></script>
    <!-- END JS -->
  </body>
</html>